parameters:
#    hexmedia_admin.example.class: Hexmedia\UserBundle\Example

services:
    hexmedia.twig.time_formatter:
        class: Hexmedia\TimeFormatterBundle\Twig\Extension\TimeFormatterExtension
        arguments: [ "@translator", "@hexmedia.templating.helper.time_formatter" ]
        tags:
            - { name: twig.extension }

    hexmedia.templating.helper.time_formatter:
        class: Hexmedia\TimeFormatterBundle\Templating\Helper\TimeFormatterHelper
        arguments: [ "@translator" ]
        tags:
            - { name: templating.helper, alias: time_formatter }