parameters:
#    hexmedia_admin.example.class: Hexmedia\UserBundle\Example

services:
    hexmedia.twig.time_ago:
        class: Hexmedia\TimeAgoBundle\Twig\Extension\TimeAgoExtension
        arguments: [ "@translator", "@hexmedia.templating.helper.time_ago" ]
        tags:
            - { name: twig.extension }

    hexmedia.templating.helper.time_ago:
        class: Hexmedia\TimeAgoBundle\Templating\Helper\TimeAgoHelper
        arguments: [ "@translator" ]
        tags:
            - { name: templating.helper, alias: time_ago }